# Generated by Django 2.0.1 on 2018-01-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(null=True)),
                ('result', models.BooleanField()),
                ('game_id', models.IntegerField()),
                ('champ_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
