# Generated by Django 2.0.1 on 2018-01-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='summoner_id',
            new_name='account_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='summoner_id',
        ),
        migrations.AddField(
            model_name='match',
            name='account_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='timestamp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='champ_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.BigIntegerField(),
        ),
    ]
